### ISSUE TITLE
Üks UFO kustutada

### ISSUE THREAD

**Issue by Kylli** [OkuMuuseum/entu#12]
Mul tekkis eksponaatide alla üks tulnukas, keda mina ära kustutada ei oska. Aita palun!

**Comment by mitselek** [comment]
Lingi saadad?

##

**Comment by Kylli** [comment]
https://okupatsioon.entu.ee/entity/eksponaat/154938
k
1. aprill 2015 17.49 kirjutas Mihkel Putrinš notifications@github.com:

> Lingi saadad?
> 
> ## 
> 
> Sent from Fleep. Learn more at https://fleep.io/intro
>

**Comment by mitselek** [comment]
OK
