### ISSUE TITLE
Mitteavalik probleem

### ISSUE THREAD

**Issue by Kylli** [OkuMuuseum/entu#20]

**Comment by Kylli** [comment]
Ei puuduta avalikku akent, aga mul oli ühe tellimuse jaoks näha kõiki teatud inimese poolt annetatud asju. trükkisin otsingusse annetaja nime - sellega peaks ju küll kõik tema asjad välja tulema! Aga tutkit! Ei saanudki ülesannet nii hästi täita, kui tahtsin. Kas sa aimad, milles probleem võib olla? Kas sellega on võimalik ära tegeleda avaliku akna lahendamise vahel? Või oskad sa vähemalt öelda, mida mina peaksin vahepeal tegema, et see probleem laheneks. Kusjuures, probleeme tekitanud aktid on kõik aastates 2013-2014. Aga siis me olime ju juba Entuga liitunud. Ehk et asi ei saa olla ka ületoomise mehhaanikas...
Külli
Luud läks katki, parandada pole aega - jääb täna volber lendamata!

**Comment by mitselek** [comment]
said ise korda? :)

## 

Mihkel Putrinš
+372 5656 0978

**Comment by Kylli** [comment]
Ei!

**Comment by mitselek** [comment]
See laheneb, kui saab korda #21
