### ISSUE TITLE
Kõik raamatukogu asjad exceli tabelisse

### ISSUE THREAD

**Issue by Kylli** [OkuMuuseum/entu#22]
veerud: kirjeldus, autor, kood, pilt
klikitav eksponaadi peale

**Comment by Kylli** [comment]
KIIRE!

**Comment by mitselek** [comment]
https://docs.google.com/spreadsheets/d/1qJm73kpi7CNgWLeTmz6EjsGMrNEUz-2otwEa52ZLjbY
