### ISSUE TITLE
HELP! KIIRE!

### ISSUE THREAD

**Issue by Kylli** [OkuMuuseum/entu#24]
Mis on lahti entuga? Tahtsin raamatut riiulisse tagasi panna, kirjutan otsingusse "omade juures", mitte midagi, vaatan raamatu seest numbri, 019217/000, ikka mitte midagi! Samas on vastuvõtuaktis nr 1147 see raamat täiesti olemas. MIS TOIMUB?!?

**Comment by mitselek** [comment]
hehe, otsi teda eksemplaride hulgast :P
https://okupatsioon.entu.ee/entity/eksemplar/154838

**Comment by Kylli** [comment]
Otsisin, programm ei leia! Terve selle akti asju ei leia!

Külli

2015-05-06 12:31 GMT+03:00 Mihkel Putrinš notifications@github.com:

**Comment by mitselek** [comment]
otsi eksemplare, mitte eksponaate

**Comment by Kylli** [comment]
Selge, nüüd sain aru. Hea, et esimene kord nii valusalt kätte tuli - jääb
ehk meeldegi!

Külli

2015-05-06 13:18 GMT+03:00 Mihkel Putrinš notifications@github.com:
