### ISSUE TITLE
Tee palun neist siis eksemplarid

### ISSUE THREAD

**Issue by Kylli** [OkuMuuseum/entu#25]
https://okupatsioon.entu.ee/entity/vastuv6tuakt/154984
https://okupatsioon.entu.ee/entity/vastuv6tuakt/154989

**Comment by Kylli** [comment]
https://okupatsioon.entu.ee/entity/vastuv6tuakt/154989

**Comment by Kylli** [comment]
Tee palun neist siis eksemplarid

**Comment by mitselek** [comment]
ok
