### ISSUE TITLE
KIIRE Palun originaalfoto teha mitteavalikuks

### ISSUE THREAD

**Issue by Kylli** [OkuMuuseum/entu#29]

**Comment by mitselek** [comment]
Nu nii kiire vast pole. Las ta saab kõik pisipildid valmis, siis teeme. Hetkel näib, et homme õhtuks võib oodata.

## 

Mihkel Putrinš
☎ +372 5656 0978

**Comment by Kylli** [comment]
Eks kiire on suhteline mõiste.

**Comment by mitselek** [comment]
olemas
