### ISSUE TITLE
KIIRE - Kui vähegi saad, te palun avalikus aknas pildi parema hiireklahviga kopeerimine jälle võimalikuks. Kirjutan kasutusjuhendit

### ISSUE THREAD

**Issue by Kylli** [OkuMuuseum/entu#33]
Kui vähegi saad, te palun avalikus aknas pildi parema hiireklahviga kopeerimine jälle võimalikuks. Kirjutan kasutusjuhendit :)

**Comment by mitselek** [comment]
tehtud
