### ISSUE TITLE
Arhiivraamatukogu

### ISSUE THREAD

**Issue by Kylli** [OkuMuuseum/entu#8]
hoidla1 riiulid 
I/1-6, mitte I/0
II/1-6
III/1-6, mitte I/0
IV/1-6, k.a K103; v.a 013470/000 ja 016330/000
V/1-5! Kuuendat rida mitte üle viia!!!
VI/1-6
VII/1-6
VIII/1-6
IX/1-2
X/1 ja 5
XI/1, 2 ja 5
Hoidla1 karbid h1-h5 (ajakirjad Põllumajandus ja sots. põllumajandus)

Hoidla 3
f vi/ riiulitel 2-4 olevad karbid
f v/5 karbid k165, k170, k158, k159, k214
f iv/5 karbid k160-164
b vagunis  karp k79

**Comment by mitselek** [comment]
Sain sellise nimekirja:

> /Hoidla1/H1 /Hoidla1/H2 /Hoidla1/H3 /Hoidla1/H4 /Hoidla1/H5;
> /Hoidla1/I/1 /Hoidla1/I/2 /Hoidla1/I/3 /Hoidla1/I/4 /Hoidla1/I/5 /Hoidla1/I/6;
> /Hoidla1/II/1 /Hoidla1/II/2 /Hoidla1/II/3 /Hoidla1/II/4 /Hoidla1/II/5 /Hoidla1/II/6;
> /Hoidla1/III/1 /Hoidla1/III/2 /Hoidla1/III/3 /Hoidla1/III/4 /Hoidla1/III/5 /Hoidla1/III/6;
> /Hoidla1/IV/1 /Hoidla1/IV/2 /Hoidla1/IV/3 /Hoidla1/IV/4 /Hoidla1/IV/5 /Hoidla1/IV/6 /Hoidla1/IV/6/K103;
> /Hoidla1/IX/1 /Hoidla1/IX/2;
> /Hoidla1/V/1 /Hoidla1/V/2 /Hoidla1/V/3 /Hoidla1/V/4 /Hoidla1/V/5;
> /Hoidla1/VI/1 /Hoidla1/VI/2 /Hoidla1/VI/3 /Hoidla1/VI/4 /Hoidla1/VI/5 /Hoidla1/VI/6;
> /Hoidla1/VII/1 /Hoidla1/VII/2 /Hoidla1/VII/3 /Hoidla1/VII/4 /Hoidla1/VII/5 /Hoidla1/VII/6;
> /Hoidla1/VIII/1 /Hoidla1/VIII/2 /Hoidla1/VIII/3 /Hoidla1/VIII/4 /Hoidla1/VIII/5 /Hoidla1/VIII/6;
> /Hoidla1/X/1 /Hoidla1/X/5;
> /Hoidla1/XI/1 /Hoidla1/XI/2 /Hoidla1/XI/5;
> /Hoidla3/B-VII/4/K79;
> /Hoidla3/F-IV/5/K160 /Hoidla3/F-IV/5/K161 /Hoidla3/F-IV/5/K162 /Hoidla3/F-IV/5/K163 /Hoidla3/F-IV/5/K164;
> /Hoidla3/F-V/5/K158 /Hoidla3/F-V/5/K159 /Hoidla3/F-V/5/K165 /Hoidla3/F-V/5/K170 /Hoidla3/F-V/5/K214;
> /Hoidla3/F-VI/2/H30 /Hoidla3/F-VI/2/H31 /Hoidla3/F-VI/2/H32 /Hoidla3/F-VI/2/H33 /Hoidla3/F-VI/2/H34 /Hoidla3/F-VI/2/H35 /Hoidla3/F-VI/2/H36 /Hoidla3/F-VI/2/H37 /Hoidla3/F-VI/2/H38;
> /Hoidla3/F-VI/3/H39 /Hoidla3/F-VI/3/H40 /Hoidla3/F-VI/3/H41 /Hoidla3/F-VI/3/H42 /Hoidla3/F-VI/3/H43 /Hoidla3/F-VI/3/H44 /Hoidla3/F-VI/3/H45 /Hoidla3/F-VI/3/H46 /Hoidla3/F-VI/3/H47;
> /Hoidla3/F-VI/4/H24 /Hoidla3/F-VI/4/H48 /Hoidla3/F-VI/4/H49 /Hoidla3/F-VI/4/H50 /Hoidla3/F-VI/4/H51 /Hoidla3/F-VI/4/H52 /Hoidla3/F-VI/4/H53 /Hoidla3/F-VI/4/H54 /Hoidla3/F-VI/4/H55

Need kaks erandit (013470/000 ja 016330/000) on mispärast teistega koos?

``` sql
SELECT DISTINCT asp.value_display
FROM entity ase
LEFT JOIN property p ON p.value_reference = ase.id
LEFT JOIN property asp ON asp.entity_id = ase.id
WHERE ase.entity_definition_keyname = 'cl-asukoht'
  AND p.property_definition_keyname = 'eksponaat-asukoht'
  AND asp.property_definition_keyname = 'cl-asukoht-path'
  AND ase.is_deleted = 0
  AND p.is_deleted = 0
  AND asp.is_deleted = 0
  AND (asp.value_display REGEXP '/hoidla1/i/[123456]'
       OR asp.value_display REGEXP '/hoidla1/ii/[123456]'
       OR asp.value_display REGEXP '/hoidla1/iii/[123456]'
       OR asp.value_display REGEXP '/hoidla1/iv/'
       OR asp.value_display REGEXP '/hoidla1/v/[12345]'
       OR asp.value_display REGEXP '/hoidla1/vi/'
       OR asp.value_display REGEXP '/hoidla1/vii/'
       OR asp.value_display REGEXP '/hoidla1/viii/'
       OR asp.value_display REGEXP '/hoidla1/ix/[12]'
       OR asp.value_display REGEXP '/hoidla1/x/[15]'
       OR asp.value_display REGEXP '/hoidla1/xi/[125]'
       OR asp.value_display REGEXP '/hoidla1/h[12345]'
       OR asp.value_display REGEXP '/hoidla3/b.*/k79'
       OR asp.value_display REGEXP '/hoidla3/f-iv/5/k16[01234]'
       OR asp.value_display REGEXP '/hoidla3/f-v/5/k'
       OR asp.value_display REGEXP '/hoidla3/f-vi/[234]')
ORDER BY asp.value_display DESC
```

**Comment by Kylli** [comment]
Ega mul ju vahet ei ole, mis mul kus on :) See on selgituseks nende kahe
erandi osas. Need on visiitkaardimapid ja ühed kaaned. Hea riiulisse panna,
aga ei ole raamatukogu.
Ülejäänu, tundub, on need, mis moodustavadki arhiivraamatukogu.

Külli

2015-04-27 14:33 GMT+03:00 Mihkel Putrinš notifications@github.com:

**Comment by mitselek** [comment]
Eksponaatide kuuluvus on nüüd Arhiivraamatukogu
